<span style="font-size: 20px;">Testing the model</span>

In [1]:
import pandas as pd
import pickle
import csv
import numpy as np

filename = 'Prudential_Life_Insurance_test.csv'

In [2]:
df_test = pd.read_csv(filename)
display(df_test.head(10))
id_col = df_test['Id'].values

,Id,Product_Info_1,Product_Info_2,Product_Info_3,Product_Info_4,Product_Info_5,Product_Info_6,Product_Info_7,Ins_Age,Ht,...,Medical_Keyword_39,Medical_Keyword_40,Medical_Keyword_41,Medical_Keyword_42,Medical_Keyword_43,Medical_Keyword_44,Medical_Keyword_45,Medical_Keyword_46,Medical_Keyword_47,Medical_Keyword_48
0,1,1,D3,26,0.487179,2,3,1,0.611940,0.781818,...,0,0,0,0,0,0,0,0,0,0
1,3,1,A2,26,0.076923,2,3,1,0.626866,0.727273,...,0,0,0,0,0,0,0,0,0,0
2,4,1,D3,26,0.144667,2,3,1,0.582090,0.709091,...,0,0,0,0,0,0,0,0,0,0
3,9,1,A1,26,0.151709,2,1,1,0.522388,0.654545,...,0,0,0,0,0,0,0,0,1,1
4,12,1,A1,26,0.076923,2,3,1,0.298507,0.672727,...,0,0,0,0,0,0,0,0,0,0
5,13,1,D3,26,0.230769,2,3,1,0.567164,0.818182,...,0,0,0,0,0,0,0,0,0,0
6,21,1,A3,26,1.000000,2,3,1,0.298507,0.690909,...,0,0,0,0,0,0,0,0,0,0
7,28,1,D4,26,0.256410,2,3,1,0.059701,0.654545,...,0,0,0,0,0,0,0,0,0,0
8,30,1,D3,26,0.076923,2,3,1,0.611940,0.618182,...,0,0,0,0,0,0,0,0,0,0
9,36,1,A3,26,0.076923,2,3,1,0.328358,0.781818,...,0,0,0,0,0,0,0,0,0,0

In [3]:
df_test['Medical_History_2'] = df_test['Medical_History_2'].astype('float64')
for c in df_test.columns:
    if df_test[c].dtype == 'int64' or df_test[c].dtype == 'object':
        df_test[c] = df_test[c].astype('category')

In [4]:
model = pickle.load(open('model.save', 'rb'))
results = model.predict(df_test.drop(columns='Id')) + np.ones(shape = df_test.shape[0], dtype= 'int64')

In [5]:
df_dict = {'Id': id_col, 'Response': results}
results_df = pd.DataFrame(df_dict)

file_path = 'Prudential_Life_insurance_results.csv'
results_df.to_csv(file_path, index=False, quoting=csv.QUOTE_NONNUMERIC)